Estudo sobre Análise de Dados

In [46]:
import numpy as np

In [47]:
# cria uma matriz unidimensional
mt = np.array([12,34,26,18,10])
print(mt)
print(type(mt))

[12 34 26 18 10]
<class 'numpy.ndarray'>


In [48]:
# cria uma array com float
mtfloat = np.array([1, 2, 3], dtype = np.float64)
print(mtfloat)
print(type(mtfloat))

# cria uma array com inteiro
mtint = np.array([1, 2, 3], dtype = np.int32)
print(mtint)
print(type(mtint))

[1. 2. 3.]
<class 'numpy.ndarray'>
[1 2 3]
<class 'numpy.ndarray'>


In [49]:
# mudar o tipo de array
# Podemos transformar tipos de dados de arrays

mtnew = np.array([1.4, 3.6, -5.1, 9.42, 4.9999]) 
print(mtnew)

# Quando transformamos de float para int os valores são truncados
mtnewint = mtnew.astype(np.int32)
print(mtnewint)

[ 1.4     3.6    -5.1     9.42    4.9999]
[ 1  3 -5  9  4]


In [50]:
# Podemos fazer o inverso também
mt5 = np.array([1, 2, 3, 4])
print(mt5)
mt6 = mt5.astype(float)
print(mt6)

[1 2 3 4]
[1. 2. 3. 4.]


In [51]:
# Mais de uma dimensão
# Cria uma matriz bidimensional

mt7 = np.array([[7, 2, 23], [12, 27, 4], [5, 34, 23]])
print(mt7)


[[ 7  2 23]
 [12 27  4]
 [ 5 34 23]]


In [52]:
# cria arrays vazio tipificados
# empty significa que não são inicializados, não que são vazios

vazio = np.empty([3, 2], dtype = int)
print(vazio)
print('------------------------------------------------')

# Cria uma matriz 4x3 com valores zero - matriz 4x3 são 4 linhas e 3 colunas
zeros = np.zeros([4, 3])
print(zeros)
print('------------------------------------------------')

# Cria uma matriz 5x7 com valores igual a 1 - matriz 5x7 são 5 linhas e 7 colunas
um = np.ones([5, 7])
print(um)
print('------------------------------------------------')

# Cria uma matriz quadrada com diagonal principal com valores 1 e os outros valores zero
diagonal = np.eye(5)
print(diagonal)

[[         0 1072693248]
 [         0 1073741824]
 [         0 1074266112]]
------------------------------------------------
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
------------------------------------------------
[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]
------------------------------------------------
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [53]:
# valores aleatórios entre zero e um

ale = np.random.random((5))
print(ale)
print('---------------------------------------------------')

# valores aleatórios distribuição normal contendo negativos

ale2 = np.random.randn((5))
print(ale2)
print('---------------------------------------------------')

# valores aleatórios numa matriz 3 x 4

ale3 = (10*np.random.random((3,4)))
print(ale3)
print('---------------------------------------------------')

[0.92960101 0.8940747  0.97223931 0.93899349 0.29478223]
---------------------------------------------------
[-0.49449949 -1.64853568  0.4872542   0.16291581 -0.03569007]
---------------------------------------------------
[[2.41294598 6.51196225 4.92710561 0.50968515]
 [6.31601478 0.49848379 4.4286178  2.59944445]
 [8.37098541 8.30347336 8.88152629 3.57297483]]
---------------------------------------------------


In [54]:
# Outra forma de gerar números aleatórios
# Uso de sementes

gnr = np.random.default_rng(1) # (1) --> semente
ale5 = gnr.random(3)
print(ale5)

# gerar números aleatórios inteiros

ale6 = gnr.integers(10, size=(3,4))
print(ale6)

[0.51182162 0.9504637  0.14415961]
[[8 9 2 3]
 [8 4 2 8]
 [2 4 6 5]]


In [55]:
# unique remove repetições

j = np.array([1, 2, 3, 4, 5, 2, 3, 6, 7, 8, 9, 6, 7, 8, 9])
j = np.unique(j)
print(j)

[1 2 3 4 5 6 7 8 9]


In [56]:
# Funções especificas 

# Cria a matriz bidimensional k
k = np.array([[17,22,43], [27,25,14],[15,24,32]])

# Mostra a matriz k
print(k)

# Mostra um elemento especifico da matriz k
print(k[0][1])

# Mostra o tamanho da matriz
print(k.shape)

[[17 22 43]
 [27 25 14]
 [15 24 32]]
22
(3, 3)


In [57]:
# Funções Matemáticas

# Mostra o maior valor da matriz k
print(k.max())

# Mostra o menor valor da matriz k
print(k.min())

# Mostra a soma dos valores da matriz k
print(k.sum())

# Mostra o valor da média dos valores da matriz k
print(k.mean())

# Mostra o valor do desvio padrão (standard deviation) dos valores da matriz k
print(k.std())


43
14
219
24.333333333333332
8.615231988880057


In [58]:
# Funções Universais, aplicadas a todos os elementos

# Mostra o valor da raiz quadrada de todos os elementos
k1 = np.array([1, 4, 9, 16, 25, 36])
print(np.sqrt(k1))

# Mostra o valor do exponencial de todos elementos
print(np.exp(k1))


[1. 2. 3. 4. 5. 6.]
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06
 7.20048993e+10 4.31123155e+15]


In [59]:
# Extração de elementos

m = np.array([1, 2, 3, 4, 5, 6])
print(m[1])
print('---------------------------------------------')

# Mostra a array criado a partir da posição 0, dois elementos
print(m[0:2])
print('---------------------------------------------')

# Mostra o array criado a partir da posição index 1
# até todo o restante do array
print(m[1:])
print('---------------------------------------------')

# Mostra o array criado a partir da antepenúltima
# posição até o final
print(m[-3:])


2
---------------------------------------------
[1 2]
---------------------------------------------
[2 3 4 5 6]
---------------------------------------------
[4 5 6]


In [60]:
# Extração de linhas e colunas

l = np.array([[4, 5], [6, 1], [7, 4]])
print(l)
print('-----------------------------------------------------')

# Primeira linha, todas as colunas
l_linha_1 = l[0, :]
print(l_linha_1)
print('-----------------------------------------------------')

# Segunda linha, todas as colunas
l_linha_2 = l[1, :]
print(l_linha_2)
print('-----------------------------------------------------')

# Terceira linha, todas as colunas
l_linha_3 = l[2, :]
print(l_linha_3)
print('-----------------------------------------------------')

# Todas as linhas, primeira coluna
l_coluna_1 = l[:, 0]
print(l_coluna_1)
print('-----------------------------------------------------')

# Todas as linhas, segunda coluna
l_coluna_2 = l[:, 1]
print(l_coluna_2)
print('-----------------------------------------------------')

[[4 5]
 [6 1]
 [7 4]]
-----------------------------------------------------
[4 5]
-----------------------------------------------------
[6 1]
-----------------------------------------------------
[7 4]
-----------------------------------------------------
[4 6 7]
-----------------------------------------------------
[5 1 4]
-----------------------------------------------------


In [61]:
# Adição e multiplicação de matrizes

n = np.array([[1, 2], [3, 4]])
o = np.array([[1, 1], [1, 1]])

# Adição de matrizes
res1 = n + o
print(res1)
print('-----------------------------------------------------')

# Multiplicação de matrizes com matrizes iguais
print(res2)
print('-----------------------------------------------------')

# Multiplicação de matrizes com matrizes diferentes
p = np.array([[1, 2], [3, 4], [5, 6]])
q = np.array([[2, 1]])
print(p + q)
print('-----------------------------------------------------')

[[2 3]
 [4 5]]
-----------------------------------------------------
[[2 3]
 [4 5]]
-----------------------------------------------------
[[3 3]
 [5 5]
 [7 7]]
-----------------------------------------------------


In [62]:
# Transposição, rearranja um conjunto de 15 elementos de 0 a 14
# em 3 linhas e 5 colunas

f = np.arange(15).reshape((3, 5))
print(f)
print('-----------------------------------------------------')

# Transforma uma matriz 3x5, em uma matriz 5x3
s = f.T
print(s)
print('-----------------------------------------------------')

# Outra forma de fazer essa transposição

s = f.transpose((1,0))
print(s)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
-----------------------------------------------------
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]
-----------------------------------------------------
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [63]:
# Expressões lógicas
# Usando where

# Criando matriz com valores aleatórios positivos e negativos
v = np.random.randn(4, 4)
print(v)
print('-----------------------------------------------------')

# Criando matriz com valores booleanos baseado na array v
x = (v > 0)
print(x)
print('-----------------------------------------------------')

# Criando matriz com valores -1 e 1 baseados nos valores da array x
z = np.where(x > 0, 1, -1)
print(z)

[[-0.48046048  0.06737429  2.20905034  1.43594464]
 [-0.36266094 -0.20861755 -0.67394787  1.58406945]
 [ 1.60816059 -0.00547364 -0.9372063  -0.50836519]
 [ 0.26689399  0.31950004 -0.32838995  0.87554548]]
-----------------------------------------------------
[[False  True  True  True]
 [False False False  True]
 [ True False False False]
 [ True  True False  True]]
-----------------------------------------------------
[[-1  1  1  1]
 [-1 -1 -1  1]
 [ 1 -1 -1 -1]
 [ 1  1 -1  1]]
