Estudo sobre Análise de Dados

In [1]:
import numpy as np

In [3]:
# cria uma matriz unidimensional
mt = np.array([12,34,26,18,10])
print(mt)
print(type(mt))

[12 34 26 18 10]
<class 'numpy.ndarray'>


In [7]:
# cria uma array com float
mtfloat = np.array([1, 2, 3], dtype = np.float64)
print(mtfloat)
print(type(mtfloat))

# cria uma array com inteiro
mtint = np.array([1, 2, 3], dtype = np.int32)
print(mtint)
print(type(mtint))

[1. 2. 3.]
<class 'numpy.ndarray'>
[1 2 3]
<class 'numpy.ndarray'>


In [12]:
# mudar o tipo de array
# Podemos transformar tipos de dados de arrays

mtnew = np.array([1.4, 3.6, -5.1, 9.42, 4.9999]) 
print(mtnew)

# Quando transformamos de float para int os valores são truncados
mtnewint = mtnew.astype(np.int32)
print(mtnewint)

[ 1.4     3.6    -5.1     9.42    4.9999]
[ 1  3 -5  9  4]


In [10]:
# Podemos fazer o inverso também
mt5 = np.array([1, 2, 3, 4])
print(mt5)
mt6 = mt5.astype(float)
print(mt6)

[1 2 3 4]
[1. 2. 3. 4.]


In [15]:
# Mais de uma dimensão
# Cria uma matriz bidimensional

mt7 = np.array([[7, 2, 23], [12, 27, 4], [5, 34, 23]])
print(mt7)


[[ 7  2 23]
 [12 27  4]
 [ 5 34 23]]


In [29]:
# cria arrays vazio tipificados
# empty significa que não são inicializados, não que são vazios

vazio = np.empty([3, 2], dtype = int)
print(vazio)
print('------------------------------------------------')

# Cria uma matriz 4x3 com valores zero - matriz 4x3 são 4 linhas e 3 colunas
zeros = np.zeros([4, 3])
print(zeros)
print('------------------------------------------------')

# Cria uma matriz 5x7 com valores igual a 1 - matriz 5x7 são 5 linhas e 7 colunas
um = np.ones([5, 7])
print(um)
print('------------------------------------------------')

# Cria uma matriz quadrada com diagonal principal com valores 1 e os outros valores zero
diagonal = np.eye(5)
print(diagonal)

[[         0 1072693248]
 [         0 1073741824]
 [         0 1074266112]]
------------------------------------------------
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
------------------------------------------------
[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]
------------------------------------------------
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
